trigger: none

pr:
- main
- release/*


variables:
- template: /build-tools/automation/variables.yml
- name: ToolchainArtifactName
  value: android-llvm-toolchain-unsigned

stages:
- template: /yaml-templates/stage-build.yml
  parameters:
    use1ESTemplate: false

- template: /yaml-templates/stage-package.yml
  parameters:
    use1ESTemplate: false
